// UpdateLocomotives.spec.ts – test suite for editing a locomotive (positive & negative)
import { test, expect, Page } from '@playwright/test';

// Use the storage state generated by auth.setup.spec.ts
test.use({ storageState: 'storageState.json' });

/**
 * Helper to navigate to the edit page of the first locomotive in the list.
 * Adjust selectors if the UI differs.
 */

async function goToFirstEdit(page: Page) {
    // Go to the list page
    await page.goto('https://iris-beta.kai.id/locotrack/locomotives');
    await expect(page).toHaveURL(/\/locotrack\/locomotives/);
    const searchInput = page.locator('#customSearchInput');

    // Pastikan input terlihat
    await expect(searchInput).toBeVisible();

    // Gunakan parameter text (jangan hardcode)
    await searchInput.fill('CC111111');
    await searchInput.press('Enter');

    // Wait for at least one edit button to appear and click it
    const firstEditBtn = page.locator('button.edit-btn-custom.btn-outline-primary').first();
    await expect(firstEditBtn).toBeVisible();
    await firstEditBtn.click();

    // Ensure we are on the edit form (URL contains /edit or /update)
    await expect(page).toHaveURL(/\/locotrack\/locomotives\/update/);
}

test.describe('Locomotives – Update (Edit) – Positive & Negative', () => {
    test.beforeEach(async ({ page }) => {
        await goToFirstEdit(page);
    });

    // ---------------------------------------------------------------------
    // Positive scenario – update a field successfully
    // ---------------------------------------------------------------------
    test('should update locomotive successfully with valid data', async ({ page }) => {
        // Change the name to a unique value to avoid duplicate conflicts
        const newName = `CC1112222`;
        await page.fill('#name', newName);

        // Submit the form
        await page.locator('button[type="submit"]').click();

        // Expect a success toast/notification (adjust text if UI differs)
        await expect(page.getByText('Update data success.')).toBeVisible({ timeout: 10000 });

        // Verify that the list now shows the updated name (quick sanity check)
        await page.goto('https://iris-beta.kai.id/locotrack/locomotives');
        // await expect(page.getByText(newName)).toBeVisible();
    });

    // ---------------------------------------------------------------------
    // Negative scenario – required fields left empty
    // ---------------------------------------------------------------------
    test('should display validation errors when required fields are empty', async ({ page }) => {
        // Clear a required field (e.g., ID) and submit
        await page.fill('#vtdid', '');
        await page.locator('button[type="submit"]').click();

        await expect(page.getByText('Field ID Locotrack is required.')).toBeVisible();
        await expect(page.getByText('Field No Sarana is required.')).toBeVisible();
        await expect(page.getByText('Field No GSM is required.')).toBeVisible();
        await expect(page.getByText('Field Dipolok is required.')).toBeVisible();
        await expect(page.getByText('Field GPS Group is required.')).toBeVisible();
    });

    // ---------------------------------------------------------------------
    // Negative scenario – invalid GSM number (non‑numeric)
    // ---------------------------------------------------------------------
    test('should show error when GSM contains non‑numeric characters', async ({ page }) => {
        await page.fill('#no_gsm', 'ABCDEF'); // invalid GSM
        await page.locator('button[type="submit"]').click();

        await expect(page.getByText('No GSM hanya boleh angka.')).toBeVisible();
    });

    // ---------------------------------------------------------------------
    // Negative scenario – duplicate ID (attempt to change ID to an existing one)
    // ---------------------------------------------------------------------
    test('should display duplicate error when ID already exists', async ({ page }) => {
        // Use a known existing ID – replace with an actual value from your data set
        const existingId = 'S123222';
        await page.fill('#vtdid', existingId);
        await page.locator('button[type="submit"]').click();

        await expect(page.getByText('Id Locotrack sudah digunakan.')).toBeVisible();
    });
});
